Eateroo/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eateroo.Data;
using Eateroo.Models;
using Eateroo.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eateroo.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetail.ManagerUser)]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        // INDEX --------------------------------------------------------------
        // GET
        public async Task<IActionResult> Index()
        {
            return View(await _db.Category.ToListAsync());
        }

        // CREATE -------------------------------------------------------------
        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (category == null)
            {
                return UnprocessableEntity();
            }

            if (!ModelState.IsValid)
            {
                return View(category);
            }

            _db.Add(category);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // EDIT ---------------------------------------------------------------
        // GET
        public async Task<IActionResult> Edit(int id)
        {
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (category == null)
            {
                return UnprocessableEntity();
            }

            if (!ModelState.IsValid)
            {
                return View(category);
            }

            _db.Update(category);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // DETAIL --------------------------------------------------------------
        // GET
        public async Task<IActionResult> Detail(int id)
        {
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // DELETE -------------------------------------------------------------
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            _db.Category.Remove(category);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Eateroo/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Eateroo.Data;
using Eateroo.Models;
using Eateroo.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eateroo.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetail.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Coupon Coupon { get; set; }

        // INDEX --------------------------------------------------------------
        // GET
        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupon.ToListAsync());
        }

        // CREATE -------------------------------------------------------------
        // GET
        public IActionResult Create()
        {
            Coupon = new Coupon();
            return View(Coupon);
        }

        // POST
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostCreate()
        {
            if (!ModelState.IsValid)
            {
                return View(Coupon);
            }

            var files = Request.Form.Files;

            if (files.Any())
            {
                byte[] imageData = null;

                using (var fs = files[0].OpenReadStream())
                {
                    using (var ms = new MemoryStream())
                    {
                        await fs.CopyToAsync(ms);
                        imageData = ms.ToArray();
                    }
                }

                Coupon.Image = imageData;
            }

            _db.Coupon.Add(Coupon);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // EDIT ---------------------------------------------------------------
        // GET
        public async Task<IActionResult> Edit(int id)
        {
            Coupon = await _db.Coupon.FindAsync(id);
            if (Coupon == null)
            {
                return NotFound();
            }

            return View(Coupon);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit()
        {
            if (!ModelState.IsValid)
            {
                return View(Coupon);
            }

            var couponFromDb = await _db.Coupon.FindAsync(Coupon.Id);
            if (couponFromDb == null)
            {
                return NotFound();
            }

            var files = Request.Form.Files;

            if (files.Any())
            {
                byte[] imageData = null;

                using (var fs = files[0].OpenReadStream())
                {
                    using (var ms = new MemoryStream())
                    {
                        await fs.CopyToAsync(ms);
                        imageData = ms.ToArray();
                    }
                }

                couponFromDb.Image = imageData;
            }

            couponFromDb.Name = Coupon.Name;
            couponFromDb.CouponType = Coupon.CouponType;
            couponFromDb.Discount = Coupon.Discount;
            couponFromDb.MinimumAmount = Coupon.MinimumAmount;
            couponFromDb.IsActive = Coupon.IsActive;
            
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // DETAIL -------------------------------------------------------------
        // GET
        public async Task<IActionResult> Detail(int id)
        {
            Coupon = await _db.Coupon.FindAsync(id);
            if (Coupon == null)
            {
                return NotFound();
            }

            return View(Coupon);
        }

        // DELETE -------------------------------------------------------------
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var couponFromDb = await _db.Coupon.FindAsync(id);
            if (couponFromDb == null)
            {
                return NotFound();
            }

            _db.Coupon.Remove(couponFromDb);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Eateroo/Areas/Admin/Controllers/SubCategoryController.cs
using Eateroo.Data;
using Eateroo.Models;
using Eateroo.Models.ViewModels;
using Eateroo.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Eateroo.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetail.ManagerUser)]
    [Area("Admin")]
    public class SubCategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SubCategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        // INDEX --------------------------------------------------------------
        // GET
        public async Task<IActionResult> Index()
        {
            return View(await _db.SubCategory.Include(s => s.Category).ToListAsync());
        }

        // CREATE -------------------------------------------------------------
        // GET
        public async Task<IActionResult> Create()
        {
            var viewModel = await CreateSubCategoryAndCategoryViewModelInstance();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubCategoryAndCategoryViewModel viewModel)
        {
            if (viewModel == null)
            {
                return UnprocessableEntity();
            }

            if (!ModelState.IsValid)
            {
                var newViewModel = await CreateSubCategoryAndCategoryViewModelInstance(viewModel.SubCategory);
                return View(newViewModel);
            }

            var isSubCategoryExists = _db.SubCategory
                .Include(s => s.Category)
                .Any(s => s.Name == viewModel.SubCategory.Name && s.CategoryId == viewModel.SubCategory.CategoryId);

            if (isSubCategoryExists)
            {
                var newViewModel = await CreateSubCategoryAndCategoryViewModelInstance(viewModel.SubCategory);
                newViewModel.Message = "Error : The Sub Category Name already exists for the selected Category. Please enter another name.";
                return View(newViewModel);
            }

            _db.SubCategory.Add(viewModel.SubCategory);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [ActionName("GetSubCategories")]
        public async Task<IActionResult> GetSubCategories(int id)
        {
            var subCategories = await (from subCategory in _db.SubCategory
                                       where subCategory.CategoryId == id
                                       orderby subCategory.Name
                                       select subCategory).ToListAsync();

            return Json(new SelectList(subCategories, "Id", "Name"));
        }

        // EDIT ---------------------------------------------------------------
        // GET
        public async Task<IActionResult> Edit(int id)
        {
            var subCategory = await _db.SubCategory.FindAsync(id);
            if (subCategory == null)
            {
                return NotFound();
            }

            var viewModel = await CreateSubCategoryAndCategoryViewModelInstance(subCategory);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SubCategoryAndCategoryViewModel viewModel)
        {
            if (viewModel == null)
            {
                return UnprocessableEntity();
            }

            if (!ModelState.IsValid)
            {
                var newViewModel = await CreateSubCategoryAndCategoryViewModelInstance(viewModel.SubCategory);
                return View(newViewModel);
            }

            var isSubCategoryExists = _db.SubCategory
                .Include(s => s.Category)
                .Any(s => s.Name == viewModel.SubCategory.Name && s.CategoryId == viewModel.SubCategory.CategoryId);

            if (isSubCategoryExists)
            {
                var newViewModel = await CreateSubCategoryAndCategoryViewModelInstance(viewModel.SubCategory);
                newViewModel.Message = "Error : The Sub Category Name already exists for the selected Category. Please enter another name.";
                return View(newViewModel);
            }

            var subCategory = await _db.SubCategory.FindAsync(viewModel.SubCategory.Id);
            if (subCategory == null)
            {
                return NotFound();
            }

            // Update only the specific properties
            subCategory.CategoryId = viewModel.SubCategory.CategoryId;
            subCategory.Name = viewModel.SubCategory.Name;
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // DETAIL ---------------------------------------------------------------
        // GET
        public async Task<IActionResult> Detail(int id)
        {
            var subCategory = await _db.SubCategory.Include(s => s.Category).FirstOrDefaultAsync(s => s.Id == id);
            if (subCategory == null)
            {
                return NotFound();
            }
            
            return View(subCategory);
        }

        // DELETE -------------------------------------------------------------
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var subCategory = await _db.SubCategory.FindAsync(id);
            if (subCategory == null)
            {
                return NotFound();
            }

            _db.SubCategory.Remove(subCategory);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        private async Task<SubCategoryAndCategoryViewModel> CreateSubCategoryAndCategoryViewModelInstance(SubCategory subCategory = null)
        {
            return new SubCategoryAndCategoryViewModel()
            {
                CategoryList = await _db.Category.ToListAsync(),
                SubCategory = subCategory ?? new SubCategory(),
                SubCategoryList = await _db.SubCategory.OrderBy(s => s.Name).Select(s => s.Name).ToListAsync()
            };
        }
    }
}

Eateroo/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Eateroo.Data;
using Eateroo.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Eateroo.Areas.Admin.Controllers
{
    [Authorize(Roles = StaticDetail.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        // INDEX --------------------------------------------------------------
        // GET
        public async Task<IActionResult> Index()
        {
            // Get the currently logged-in user
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim == null)
            {
                return Redirect("/Identity/Account/Login");
            }

            // Pass-in the list of user except the currently logged-in user
            return View(await _db.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync());
        }

        // LOCK ---------------------------------------------------------------
        // POST
        public async Task<IActionResult> Lock(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await _db.ApplicationUser.FindAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            user.LockoutEnd = DateTime.Now.AddYears(1000);
            await _db.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }

        // UNLOCK -------------------------------------------------------------
        // POST
        public async Task<IActionResult> Unlock(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await _db.ApplicationUser.FindAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            user.LockoutEnd = null;
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Eateroo/Views/Shared/_CreateAndBackToListButtonPartial.cshtml
<input type="submit" value="Create" class="btn btn-info btn-width form-control" />
<a asp-action="Index" class="btn btn-secondary btn-width form-control ml-3">Back to List</a>

Eateroo/Views/Shared/_CreateButtonPartial.cshtml
<a class="btn btn-info text-white" asp-action="Create">
    <i class="fas fa-plus"></i>&nbsp; Create
</a>

Eateroo/Views/Shared/_DetailAndBackToListButtonPartial.cshtml
@model int
<a asp-action="Edit" asp-route-id="@Model" class="btn btn-info btn-width form-control">Edit</a>
<a asp-action="Index" class="btn btn-secondary btn-width form-control ml-3">Back to List</a>

Eateroo/Views/Shared/_Layout.cshtml
@using Eateroo.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eateroo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
              integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
              crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
              integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
              crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="body-bg">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-utensils"></i>&nbsp; Eateroo
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation" style="outline:none">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <div class="navbar-nav flex-grow-1">

                        @if (User.IsInRole(StaticDetail.ManagerUser))
                        {
                            <div class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Content Management</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="SubCategory" asp-action="Index">Sub Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="MenuItem" asp-action="Index">Menu Item</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon" asp-action="Index">Coupons</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </div>
                        }

                        <a class="nav-item nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">
                            @{
                                int cartTotalCount = 0;
                                var count = HttpContextAccessor.HttpContext.Session.GetInt32(StaticDetail.ShoppingCartCount);
                                if (count.HasValue)
                                {
                                    cartTotalCount = count.Value;
                                }
                            }
                            <i class="fas fa-shopping-cart"></i> (@cartTotalCount)
                        </a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-light">
        <div class="container text-center">
            &copy; 2019 - Eateroo
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=37yrgjrsokrg710tctwvp0i25clq7rgr550m01ck1rvtajbt"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=37yrgjrsokrg710tctwvp0i25clq7rgr550m01ck1rvtajbt"></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Eateroo/Views/Shared/_MenuItemsAreaPartial.cshtml
@model IEnumerable<MenuItem>

@if(Model.Any())
{
    <div class="col-12 pb-4 post @Model.FirstOrDefault().Category.Name.Replace(" ", string.Empty) menu-restaurant">
        <h3 class="text-info">@Model.FirstOrDefault().Category.Name</h3>

        @foreach(var item in Model)
        {
            <div class="border border-info rounded m-3 p-3">
                <div class="row">
                    <div class="col-md-3">
                        <img src="@item.Image" class="img-fluid card" />
                    </div>

                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-8">
                                <label class="text-dark" style="font-size:21px;">@item.Name</label>
                                @if(item.Spiciness == "1")
                                {
                                    <img src="~/images/spicy.png" title="Spicy" class="tooltip-target" style="width:25px" />
                                }
                            </div>
                            <div class="col-4 text-right">
                                <h4>$@item.Price.ToString("0.00")</h4>
                            </div>
                        </div>

                        <div class="row d-none d-md-block">
                            <div class="col-12 text-justify">
                                <p>@Html.Raw(item.Description)</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="offset-md-9 col-md-3 text-center">
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info form-control">Details</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        }

    </div>
}

Eateroo/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "info";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Eateroo/Views/Shared/_TableButtonsPartial.cshtml
@model  int

<td class="text-right" style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white tooltip-target" asp-action="Edit" asp-route-id="@Model" title="Edit">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-info text-white tooltip-target" asp-action="Detail" asp-route-id="@Model"  title="Detail">
            <i class="fas fa-list-alt"></i>
        </a>

        @{ var deleteModalId = "deleteModal" + Model; }
        @{ var deleteModalIdRef = "#deleteModal" + Model; }
        @{ var deleteModalLabelId = "deleteModalLabel" + Model; }
        <button type="button" class="btn btn-danger text-white tooltip-target" data-toggle="modal" data-target="@deleteModalIdRef" title="Delete">
            <i class="fas fa-trash-alt"></i>
        </button>
    </div>

    <!-- Delete Modal -->
    <div class="modal fade" id="@deleteModalId" tabindex="-1" role="dialog" aria-labelledby="@deleteModalLabelId" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered justify-content-center" role="document">
            <form method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="@deleteModalLabelId">Confirm Delete</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete the item?
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger btn-width" asp-action="Delete" asp-route-id="@Model">Yes</button>
                        <button type="button" class="btn btn-secondary btn-width" data-dismiss="modal">No</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</td>

Eateroo/Views/Shared/_UpdateAndBackToListButtonPartial.cshtml
<input type="submit" value="Update" class="btn btn-info btn-width form-control" />
<a asp-action="Index" class="btn btn-secondary btn-width form-control ml-3">Back to List</a>